### ISSUE TITLE
readme could use a better example

### ISSUE THREAD

**Issue by krilnon** [senocular/stack.js#1]
I read the readme and don't know why this model would be something I would want to switch to.  I get the gist that it's for maintaining a particular execution order when you have functions of varying runtime complexity, but I don't see why stack.js is better than my alternative choices. (I'm not really sure what the alternative(s) would be… how about a comparison?)

I _believe_ that stack.js has a place in the world, but I'm too dumb to understand its place from the readme so far. :question:

**Comment by senocular** [comment]
I honestly don't know either.  I had no real application in mind when I wrote it, just a passing thought of how sometimes I remember wishing I had a better defer.  When did I wish that? I forgot.  Maybe some day in the future I'll be in some situation where I'll realize that this could be used and makes sense.

I do remember thinking that I didn't trust using something like setTimeout because a frame change could potentially sneak in there changing the state of your document.  This implementation assures that the next call stack is consecutive (since you're still in the same real call stack).

I do agree that the documentation should reflect better "why" (or "where" or "how") someone would use this.

**Comment by krilnon** [comment]
Hmm, I think I might understand it a bit more.  With `setTimeout(0)`, you can "set it and forget it" like rotisserie chicken, but there's the worry that something like `requestAnimationFrame` could slip in before that timeout happens, messing up your mental model of when the postponed event occurs?  

I guess the difference is that you have to remember to call `Stack.exec` at some point, but it gives you the advantage of being more confident about async call ordering.

**Comment by senocular** [comment]
If you run all your root methods/handlers through `Stack.invoked()`, you'll never have to worry about calling exec manually.

**Comment by senocular** [comment]
I added `deferOnce()/pushOnce()` methods which would be helpful for invalidation patterns.  Don't know if Stack really makes it any easier for them or not.

``` javascript
updateMetrics();
Stack.pushOnce(render); // invalidated
```
